export type AcademicSection = {
  title: string;
  items: string[];
}

export const academicData: Record<string, AcademicSection> = {
  international: {
    title: "Yurtdışı Tecrübesi (Observership)",
    items: [
      "Hospital Universitario del Henares, Madrid, İspanya – Karın Duvarı Cerrahisi (Dr. Miguel Angel Garcia Urena, Madrid Hernia Group)",
      "Hospital Universitario Puerta de Hierro Majadahonda, Madrid, İspanya – Karın Duvarı Cerrahisi (Dr. Javier Lopez Monclus, Madrid Hernia Group)",
      "Hospital Ramon y Cajal, Madrid, İspanya – Karın Duvarı Cerrahisi (Dr. Luis A. Blázquez Hernando, Madrid Hernia Group)",
    ],
  },
  associations: {
    title: "Dernek Üyelikleri",
    items: [
      "European Hernia Society (EHS) – ID: 3994",
      "European Association for Endoscopic Surgery (EAES) – ID: 11.810",
      "Türk Fıtık Derneği – Genç Cerrahlar Kanadı (Takım Lideri)",
      "Türk Cerrahi Derneği – ID: 4972",
    ],
  },
  conferences: {
    title: "Katıldığı Kongre ve Kurslar",
    items: [
      "2nd Dubai Hernia Summit, 2026 – Dubai",
      "47th EHS Congress, 2025 – Paris",
      "EHS Basic Abdominal Wall Surgery Course, 2025 – Paris",
      "XVIth National Abdominal Wall Surgery Congress & Hands-on Workshop, 2025 – Madrid",
      "XXth National IIIrd International Turkish Colon and Rectal Surgery Congress, 2025 – Antalya",
      "10th National Hernia Congress, 2025 – Antalya",
      "13th Gastroenterological Surgery Congress, 2025 – Antalya",
      "MOCED Foregut Academy Summit, 2025 – İzmir",
      "Innovative Procedures for Surgeons in Breast and Thyroid Diseases, 2025 – İzmir",
      "Ege University & Turkish Hernia Society Robotic Inguinal Hernia Surgery Workshop, 2025 – İzmir",
      "Surgical Research Congress, 2025",
      "Robotic Abdominal Wall Surgery Nordics Congress, 2024 – Kopenhag",
      "46th EHS Annual Conference, 2024 – Prag",
      "23rd National Surgery Congress, 2024 – Antalya",
      "3rd EHS Monothematic Conference, 2024 – Sofya",
      "Both Sides of Aegean Meet for Thyroid Cancer Summit, 2024 – İstanbul",
      "Global Surgeons Summit Hernia Academy, 2024 – İstanbul",
      "International TSCRS Autumn Symposium, 2024 – Ankara",
      "Turkish Surgical Society Hernia Surgery Days, 2024 – İzmir",
      "Ege University Inguinal Hernia Workshop, 2024 – İzmir",
      "7th National Hepatopancreatobiliary Surgery Congress, 2023 – Antalya",
      "XIXth National IInd International Turkish Colon and Rectum Surgery Congress, 2023 – Antalya",
      "Adrenalectomy Summit, 2023 – İzmir",
      "Turkish Surgical Society Anastomosis Techniques Course, 2023 – İzmir",
      "22nd National Surgery Congress, 2022 – Antalya",
      "12th International Gastrointestinal Cancers Conference, 2022 – İstanbul",
      "ISLS 2022 Single Topic Symposium: Liver Transplantation, 2022 – İstanbul",
      "Neuromonitoring and Autofluoresence Course in Thyroid Surgery, 2022 – Atina",
      "Cytoreduction and HIPEC Course in Metastatic Colorectal Cancer, 2022 – İzmir",
      "15th National & 2nd International Congress of Endoscopic and Laparoscopic Surgery, 2021 – Antalya",
      "8th National Hernia Congress, 2021 – Online",
    ],
  },
  publications: {
    title: "Ulusal ve Uluslararası Yayınlar",
    items: [
      "Korucuk E, Erozkan K, Celtik U, Ergun O, Bozbiyik O. Anterior Sagittal Anorectoplasty for Low-Type Anorectal Malformation in an Adult Female. Dis Colon Rectum. 2025.",
      "Korucuk E, Erözkan K, Bozbıyık O. House Advancement Flap for the Treatment of Post-Hemorrhoidectomy Anal Stenosis. Turk J Colorectal Dis. 2025;35(4):164-165.",
      "Korucuk E, Erozkan K, Bozbiyik O. Transillumination-guided endoscopic and transanal recanalization for total anastomotic stenosis following low anterior resection. Tech Coloproctol. 2026;30(1):31.",
      "Gümüş T, Korucuk E, Erözkan K, Demir HB, Uğuz A. A rare case of abdominal gunshot trauma: Isolated common bile duct injury. Turk J Trauma Emerg Surg. 2025;31(4):1152-1156.",
      "Gümüş T, Temel R, Korucuk E et al. Utilizing of the Lymphocyte/CRP Ratio as a Predictor of Ischemia in Acute Incarcerated Hernias. Anatol J Gen Med Res. 2025;35(2):170-177.",
      "Yasar H, Sayur V, Korucuk E et al. Early Diagnosis of Acute Rejection and Acute Tubular Necrosis After Kidney Transplantation Using MRI. Cureus 17(4): e82879. 2025.",
      "E Korucuk, T Gumus. Laparoscopic Inguinal Hernia Repair and Evaluation of Postoperative Quality of Life in Elderly Patients. BJS, Volume 111, Issue Supplement_5, May 2024.",
      "T Gumus, E Korucuk. Incisional Hernia After Liver Transplantation: Long Term Outcomes and Evaluation of Quality of Life. BJS, Volume 111, Issue Supplement_5, May 2024.",
      "Gümüş T, Korucuk E, Güler E, Türk T, Uğuz A. Akut Kolesistite Bağlı Safra Kesesi Perforasyonunun Klinik Yönetimi. ETD. 2024;64(4).",
      "Umman V, Gümüş T, Korucuk E et al. Metabolic and surgical factors affecting postoperative quality of life in patients with total pancreatectomy. Turkish Journal of Surgery, 2023;39(3):264-273.",
      "Umman V, Gumus T, Korucuk E et al. A new method for predicting alcohol relapse in liver transplantation: Barratt scale. Hepatology, 2023;4:118-122.",
      "Umman V, Gumus T, Tunali S, Temel R, Korucuk E et al. Forty-five patients with hydatid liver cysts. 2023.",
      "Demir HB, Kırçiçeği S, Korucuk E et al. TAP block efficacy in laparoscopic TAPP. Laparoscopic Endoscopic Surgical Science, 2023;30(2).",
      "Demir HB, Sertoz B, Girgin T, Korucuk E, Miftari A. Treatment of Acute Cholecystitis in the Elderly: Percutaneous Cholecystostomy vs Cholecystectomy. İzmir Eğitim Ve Araştırma Hastanesi Tıp Dergisi, Cilt 28, Sayı 1.",
      "Demir HB, Korucuk E, Miftari A, Turk Y. Have General Surgery Practices Decreased During the COVID-19 Pandemic? Cureus. 2022;14(7):e27270.",
    ],
  },
  papers: {
    title: "Ulusal ve Uluslararası Bildiriler",
    items: [
      "Bibliometric analysis of publications in abdominal wall surgery: 35-year data from Türkiye – Surgical Research Congress, 2025",
      "Inguinal hernia management: Experience of a university training hospital – Surgical Research Congress, 2025",
      "Ivor Lewis Torakotomisiz de Yapılabilir mi? – 13th Gastroenterological Surgery Congress, 2025",
      "T1 Evre Mide Adenokarsinomlarında ESD vs Cerrahi – 13th Gastroenterological Surgery Congress, 2025",
      "Impact of Robotic-Assisted Surgery vs. Laparoscopy on LARS and QoL – XX. National III Intl. Turkish Colon and Rectal Surgery Congress, 2025",
      "Publication Rates of General Surgery Specialization Theses – XX. National III Intl. Turkish Colon and Rectal Surgery Congress, 2025",
      "House Advancement Flap for Post-Hemorrhoidectomy Severe Distal Anal Stenosis – XX. National III Intl. Turkish Colon and Rectal Surgery Congress, 2025",
      "Anterior Sagittal Anorectoplasty for Anorectal Malformation – XX. National III Intl. Turkish Colon and Rectal Surgery Congress, 2025",
      "Transillumination-Guided Recanalization for Total Anastomotic Stenosis – XX. National III Intl. Turkish Colon and Rectal Surgery Congress, 2025",
      "Preferred Anesthesia Technique in Open Inguinal Hernia Repair – 47th EHS Congress, 2025 Paris",
      "Surgeon as a Key Risk Factor in Incisional Hernia Development – 47th EHS Congress, 2025 Paris",
      "Inguinal Hernia Management After Updated Guideline – 47th EHS Congress, 2025 Paris",
      "İnsizyonel Herni Gelişiminde Cerrahın Rolü – 10th National Hernia Congress, 2025",
      "Hiatal Herni Cerrahi Tedavisine Yaklaşım – 10th National Hernia Congress, 2025",
      "Karın Duvarı Cerrahisi Bibliyometrik Analizi: 35 Yıllık Türkiye Verileri – 10th National Hernia Congress, 2025",
      "Laparoscopic Inguinal Hernia Repair and QoL in Elderly Patients – 46th EHS Conference, 2024 Prag",
      "Incisional Hernia After Liver Transplantation: QoL After Repair – 46th EHS Conference, 2024 Prag",
      "T1 Evre Mide Adenokarsinomlarında ESD vs Cerrahi – 17th National Endoscopic Laparoscopic Robotic Surgery Congress, 2024",
      "Akut Kolesistite Bağlı Safra Kesesi Perforasyonu – 23rd National Surgery Congress, 2024",
      "Penetran Batın Yaralanmalarında Selektif Nonoperatif Takip – 23rd National Surgery Congress, 2024",
      "Hepatosellüler Kanserli Hastalarda Lokorejyonel Tedavi Sonrası Karaciğer Nakli – 16th Turkish Hepatobiliary Surgery Congress, 2023",
      "Total Pankreatektomilerde Vasküler Rezeksiyon Sonuçları – 16th Turkish Hepatobiliary Surgery Congress, 2023",
      "Kolorektal Kanserlerin KC Metastazlarında Mikrodalga Ablasyon – XIXth Turkish Colon and Rectum Surgery Congress, 2023",
      "T3-T4 Evre Kolon Kanserinde Laparoskopik vs Açık Cerrahi – 22nd National Surgery Congress, 2022",
      "Pandemi Döneminde Elektif Kolesistektomi ve Akut Kolesistit İlişkisi – 22nd National Surgery Congress, 2022",
      "Komorbiditesi Yüksek Hastalarda Akut Kolesistit Tedavisi – 22nd National Surgery Congress, 2022",
      "Early Complications After Surgical Treatment of Pancreatic Cancers in Elderly – 12th Intl. GI Cancers Conference, 2022",
      "Alkole Bağlı KC Yetmezliğinde Relapsı Öngörmede Barratt Ölçeği – 14th Transplantation Congress, 2022",
      "Laparoskopik Donör Nefrektomi vs Açık Donör Nefrektomi – 15th National & 2nd Intl. Congress of Endoscopic Surgery, 2021",
      "Komorbiditesi Olan Hastalarda Akut Kolesistit: Perkütan Kolesistostomi vs Kolesistektomi – 15th National & 2nd Intl. Congress of Endoscopic Surgery, 2021",
      "T3-T4 Evre Kolorektal Kanserlerde Laparoskopik Cerrahi: Ege Üniversitesi Deneyimi – 1st Intl. Turkish Colorectal Surgery Congress, 2021",
    ],
  },
  books: {
    title: "Kitap Bölümleri",
    items: [
      "Esophageal Carcinoma – INSAC Health Science",
    ],
  },
  reviews: {
    title: "Dergi Hakemlikleri",
    items: [
      "Revista da Associação Médica Brasileira",
    ],
  },
}
