export const NAME = 'Op.Dr. Ebubekir'
export const SURNAME = 'Korucuk'
export const GREEETINGS = 'Ege Üniversitesi Tıp Fakültesi’nde tıp eğitimimi tamamladıktan sonra, aynı kurumda genel cerrahi ihtisasımı tamamlayarak genel cerrahi uzmanı oldum. Alanımda birçok kurs ve bilimsel çalışmada yer aldım. Özel ilgi alanım olan fıtık cerrahisinde bilgi ve deneyimimi artırmak amacıyla yurt dışında eğitim aldım. Cerrahi kariyerime Erciş Şehit Rıdvan Çevik Devlet Hastanesi’nde devam ederken, bilimsel faaliyetlerimi de aktif olarak sürdürmekteyim. Blogumda sorularınıza yanıt bulabilir ve dijital muayenehanem aracılığıyla merak ettikleriniz için bana ulaşabilirsiniz.'
export const WHOAMI_RESUME = `
1995 yılında Erzurum’un Pasinler ilçesinde doğdum. İlk ve ortaöğretimimi Pasinler’de, lise eğitimimi ise Erzurum’da tamamladım. 2019 yılında Ege Üniversitesi Tıp Fakültesi’nden mezun oldum ve aynı yıl Ege Üniversitesi Hastanesi Genel Cerrahi Anabilim Dalı’nda genel cerrahi ihtisasına başladım.

Genel cerrahi ihtisasım süresince alanında önde gelen isimler eşliğinde çok sayıda açık ve laparoskopik ameliyata katıldım; hastaların takip ve tedavi süreçlerinde aktif rol üstlendim. Ayrıca robotik cerrahi alanında birçok operasyonda görev aldım ve kliniğimiz bünyesindeki robotik cerrahi asistan eğitim programı kapsamında robotik sistemleri laboratuvar ortamında aktif olarak kullanarak eğitim aldım.

Asistanlık sürecimde çok sayıda bilimsel çalışmada yer aldım; ulusal ve uluslararası kongre ve sempozyumlara katılarak bilimsel faaliyetlerimi sürdürdüm. Kompleks karın duvarı fıtıkları alanındaki bilgi ve deneyimimi artırmak amacıyla, Madrid’de Prof. Dr. Miguel Ángel García Ureña ve ekibinden oluşan Madrid Hernia Group bünyesinde 2 ay süreyle gözlemci cerrah olarak bulundum ve bilimsel çalışmalara katkı sağladım.

2025 yılında genel cerrahi ihtisasımı tamamladım. Şubat 2026 itibarıyla Erciş Şehit Rıdvan Çevik Devlet Hastanesi’nde genel cerrahi uzmanı olarak görev yapmaya başladım ve halen burada aktif olarak çalışmaktayım.

Başlıca ilgi alanlarım kompleks karın duvarı fıtıkları ve minimal invaziv cerrahidir. Avrupa Fıtık Derneği (EHS), Avrupa Endoskopik Cerrahi Derneği (EAES), Türk Cerrahi Derneği ve Türk Fıtık Derneği üyesiyim. Ayrıca Türk Fıtık Derneği Genç Cerrahlar Kurulu’nda yönetici üye olarak görev almakta, ülkemizde fıtık cerrahisi eğitiminin ve bilimsel çalışmaların geliştirilmesine katkı sağlamaktayım.`